name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Backend Docker Image
        run: sudo docker build -t sajinq/dryynk-backend:latest ./backend
      
      - name: Create nginx.conf for frontend
        run: |
          cat > frontend/nginx.conf <<EOL
          server {
              listen 80;
              server_name dryynk.com;
              return 301 https://www.dryynk.com$request_uri;
          }
          server {
              listen 443 ssl;
              server_name dryynk.com;
              ssl_certificate /etc/letsencrypt/live/dryynk.com/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/dryynk.com/privkey.pem;
              return 301 https://www.dryynk.com$request_uri;
          }
          server {
              listen 80;
              server_name www.dryynk.com;
              # Redirect HTTP to HTTPS
              location / {
                  return 301 https://$host$request_uri;
              }
          }

          server {
              listen 443 ssl;
              server_name www.dryynk.com;
              ssl_certificate /etc/letsencrypt/live/dryynk.com/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/dryynk.com/privkey.pem;
              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
                  try_files $uri $uri/ /index.html;
              }
              location /api {
                  proxy_pass http://dryynk-backend:5000/api;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
          EOL
          
      - name: Build Frontend Docker Image
        run: sudo docker build --no-cache -t sajinq/dryynk-frontend:latest ./frontend
      
      - name: Push Images to docker hub
        run: |
          sudo docker push sajinq/dryynk-backend:latest
          sudo docker push sajinq/dryynk-frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull images from docker hub
        run: |
          sudo docker pull sajinq/dryynk-backend:latest
          sudo docker pull sajinq/dryynk-frontend:latest
          
      - name: Delete old containers
        run: |
          sudo docker rm -f dryynk-backend || true
          sudo docker rm -f dryynk-frontend || true
          
      - name: Create Docker network
        run: sudo docker network create dryynk-network || true
          
      - name: Run Docker Containers
        run: |
          sudo docker run -d --name dryynk-backend \
            --network dryynk-network \
            -p 5000:5000 \
            -e NODE_ENV=production \
            sajinq/dryynk-backend
            
          sudo docker run -d --name dryynk-frontend \
            --network dryynk-network \
            -p 80:80 \
            -p 443:443 \
            -v /etc/letsencrypt:/etc/letsencrypt:ro \
            sajinq/dryynk-frontend